---
title: "Take-home Exercise 3"
date: "May 5, 2024"
date-modified: "last-modified"
editor: visual
---

## The Task

In this take-home exercise, you are required to apply appropriate visual analytics methods to:

-   help FishEye, a non-profit organization that focuses on illegal fishing, to better identify bias, track behavior changes, and infer temporal patterns from the knowledge graphs prepared by their data analysts, or
-   help NorthClass intuitively perceive the learning status of learners and provide feasible suggestions for adjusting teaching strategies and course designs, or
-   to help DataInsight visualise and understand industry and geographical developments, and provide actionable recommendations for talent acquisition and job search decisions.

::: callout-important
-   You only need to attempt either **one out of the three Mini Cases** (i.e. [MC1](https://vast-challenge.github.io/2024/MC1.html), [MC2](https://vast-challenge.github.io/2024/MC2.html), [MC3](https://vast-challenge.github.io/2024/MC3.html)) or [Grand Challenge](https://vast-challenge.github.io/2024/GC.html) provided in [VAST Challenge 2024](https://vast-challenge.github.io/2024/) or **Data Analysis Inspires Wisdom: Time-Series Multivariate Education Data Visual Analytics Challenge** or **Insight into Recruitment Data: Multivariate Recruitment Data Visual Analytics Challenge** of [ChinaVis 2024](https://chinavis.org/2024/english/challenge_en.html).
-   The data should be processed by using appropriate **tidyverse** family of packages and the Visual Analytics tools must be prepared by using appropriate R packages.
:::

## Assessment Rubic

-   Quality of Visual Storytelling (30%): Ability to provide visually-driven discussions and answers on the tasks and questions chosen.
-   Quality of Data Visualisation (30%): Appropriateness, functional and aesthetics of the data visualisation used.
-   Quality of Data Preparation and Wrangling (20%): Appropriateness and proficiency of using tidyverse and other related R packages to prepare and wrangle the data.
-   Quality of Reproducibility (20%): Completeness and comprehensiveness of documenting the data visualisation process including and not limited to data import, data preparation, data wrangling, data integration and data visualisation design.

## Submission Instructions

This is an individual assignment. You are required to work on the take-home exercises and prepare submission individually.

::: callout-important
The specific submission instructions are as follows:

-   The write-up of the take-home exercise must be in **Quarto html document** format. You are required to publish the write-up on [**Netlify**](https://www.netlify.com/).
-   Provide the links to the Take-home Exercise write-up and github repository onto eLearn (i.e. Take-home Exercise section)
:::

## Submission date

Your completed take-home exercise is due on ~~**2nd**~~ **9th June 2024, by 11:59 mid-night**.

## KickStarter

-   [Kickstarter 1: Working with Text Data]()
-   [Kickstarter 2: Working with Graph Data](../VAST/kickstarter2.html)
-   [Kickstarter 3: Working with Geographic Data]()

## Learning from Senior

-   [ISSS608 2016-17 T3 Assign GUAN YIFEI](https://wiki.smu.edu.sg/1617t3isss608g1/ISSS608_2016-17_T3_Assign_GUAN_YIFEI). Although this assignment was completed by using Tableau Professional but there are a lot we can learn from the submission especially the discussion of visual insights.
-   [ISSS608 2016-17 T3 Assign ZHANG YANRONG](https://wiki.smu.edu.sg/1617t3isss608g1/ISSS608_2016-17_T3_Assign_ZHANG_YANRONG). Although this assignment was completed by using QGIS and Tableau Professional but there are a lot we can learn from the submission especially the discussion of visual insights.
-   [ISSS608 2021-22 April Term Assignment 6: Ong Zhi Rong Jordan](https://isss608-jordan-va.netlify.app/th_ex6/th_ex6.html)
-   [ISSS608 2021-22 April Term Assignment 6: Raunak Kapur](https://isss608-raunakkapur.netlify.app/th_ex/the6)

**AY2022-23 April Term**

-   [ONG CHAE HUI](https://smu-isss608-vaa.netlify.app/take-home_ex/take-home_ex03/take-home_ex03#overview)
-   [KWA KAH BOON](https://cosmic-boon.netlify.app/take-home_ex/take-home_ex03/take-home_ex3)
-   [FONG BAO XIAN](https://fongbx-isss608-visual-analytics.netlify.app/take-home%20ex/take-home_ex03/take-home_ex03)
-   [HAILEY CHEONG SZE-YENN](https://isss608-ay2023-haileycsy.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

## Reference

-   [Analysis Without Data: Teaching Students to Tackle the VAST Challenge](https://par.nsf.gov/servlets/purl/10394301)
