---
title: "Take-home Exercise 1"
date: "April 13, 2024"
date-modified: "April 14, 2024"
format: html
editor: visual
---

::: {style="font-size: 200%;"}
***Creating data visualisation beyond default***
:::

## Setting the Scene

There are two major residential property market in Singapore, namely public and private housing. Public housing aims to meet the basic need of the general public with monthly household income less than or equal to S\$14,000. For families with monthly household income more than S\$14,000, they need to turn to the private residential market.

## The Task

Assuming the role of a graphical editor of a median company, you are requested to prepare minimum two and maximum three data visualisation to reveal the private residential market and sub-markets of Singapore for the 1st quarter of 2024.

## The Data

To accomplish the task, transaction data of [REALIS](https://www.ura.gov.sg/reis/index) will be used. A complete set of the private residential property transaction data from 1st January 2023 to 31st March 2024 have been downloaded via SMU e-library database service. It is available on the *Assignment -\> Take-home Exercise 1* of eLearn.

For student who are interested to download the data by yourself, please feel free to visit SMU e-library.

## The Designing Tool

The data should be processed by using appropriate **tidyverse** family of packages and the statistical graphics must be prepared using **ggplot2** and its extensions.

## The Write-up

The write-up of the take-home exercise should include but not limited to the followings:

-   A reproducible description of the procedures used to prepare the analytical visualisation. Please refer to the senior submission I shared below.

-   A write-up of not more than **150 words** per each data visualisation, describing and discussing the patterns and/or trends reveal by each visualisation prepared.

# Submission Instructions

This is an individual assignment. You are required to work on the take-home exercises and prepare submission individually.

::: callout-important
The specific submission instructions are as follows:

-   The analytical visualisation must be prepared by using **R and appropriate R packages**.
-   Limit your submission to not more than **three** data visualisation.
-   The write-up of the take-home exercise must be in **Quarto html document** format. You are required to publish the write-up on [**Netlify**](https://www.netlify.com/).
:::

## Submission date

Your completed take-home exercise is due on ~~**21st April 2024 (Sunday)**~~ **26th April 2024 (Friday) by 11:59pm mid-night**.

## Learning from senior

-   [KYLIE TAN JING YI](https://akalestale.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [TOA ZI YING JANET](https://janettoaisss608.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [LEW YING ZHEN SERENA](https://isss608-spacebun.netlify.app/take-home_ex/take-home_ex1/take-home_ex1)

## Peer Learning

- [ARYA SIAHAAN](https://isss608-aryasiahaan.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
- [CHENG CHUN CHIEH](https://zjjisss608va.netlify.app/takehomeex/ex01/takehomeex1#take-home-ex-1)
- [HA DUC TIEN](https://isss608-ay2023-24apr-hdt.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
- [HO ZI JUN](https://isss608-zjho008.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
- [JAYA GEORGE](https://isss608-jayageorge.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
- [JOSHUA TING SI YUAN]()
- [KE KE](https://isss608keke.netlify.app/takehome/takehome1)
- [KRISTINE JOY PAAS](https://isss608-kjcpaas.netlify.app/take-home_exs/ex1/take-home_ex1)
- [KWOK PEI SHAN](https://peishan0502-isss608.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
- [LIANG XIUHAO](https://va24-ry.netlify.app/take-home%20exercise/take-home_ex01/take-home_ex01)
- [LIN GUAN JHEN](https://isss608gj.netlify.app/take-home/take-home_ex1/tkx01)
- [LOH NIAN EN ALICIA](https://lnealicia-isss608.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
- [LOW JI XIONG](https://jayexx-assignmts-isss608-ay23-24-t3.netlify.app/take-home_ex/take-home_ex1/take-home_ex1)
- [MOHAMAD HAFEZ BIN SIDEK](https://hafeszsidek.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
- [QUEK YOU TING](https://isss608ytquek.netlify.app/take_home_ex/take_home_ex1)
- [SARTHAK JAGDISH NAGAPURKAR](https://isss608-vaa-sarthakj.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
- [SENG JING YI](https://jingyi-vaa.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
- [TAN FENGJI](https://main--spectacular-buttercream-d0f389.netlify.app/assignment_1)
- [TEN WEI PENG](https://weipengten-isss608.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
- [THET MYAT NOE](https://isss608-ay2023-24-tmyatnoe.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
- [WANG YUHUI]()
- [XIAO FUDI](https://xiao-fudi-2024t2.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
- [ZHANG CHENBIN](https://iss608-1.netlify.app/take-home_ex/take-home_ex01/take-home%20exercise%201)
- [ZHANG WENJING](https://cool-parfait-6916a6.netlify.app/)
- [ZOU JIAXUN](https://zoujiaxun.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)

## Reference

-   [URA releases flash estimate of 1st Quarter 2024 private residential property price index](https://www.ura.gov.sg/Corporate/Media-Room/Media-Releases/pr24-11)
-   [Unsold private housing stock on the rise ahead of ramp-up in new launches in 2024](https://www.businesstimes.com.sg/property/unsold-private-housing-stock-rise-ahead-ramp-new-launches-2024)
-   [HDB resale prices rise 1.7%; private home prices up 1.5% in first quarter: Flash estimates](https://www.channelnewsasia.com/singapore/hdb-resale-private-home-prices-rise-waiting-period-property-analysts-4233876)
